<a href="https://colab.research.google.com/github/Ftajedini/Github_Tutorial/blob/main/NLP_Text_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://github.com/lmoroney/tfbook/blob/master/chapter5/emotion_preprocess.ipynb

Data matny=corpus
لیست جملات /
استانداردسازی/
Tokenization کلمه/
Indexing عدد/
vectorization


#NLP Text pre_processing

In [4]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import TextVectorization


In [1]:
text = "I like my brother. Go home!. Do you like my brother?"

In [2]:
sentences = text.split('. ')
print(sentences)

['I like my brother', 'Go home!', 'Do you like my brother?']


#Method 1
1- Tokenization + Indexing

In [5]:
tokenizer = Tokenizer(num_words=100, oov_token='')
tokenizer.fit_on_texts(sentences)

print(tokenizer.word_index)

{'': 1, 'like': 2, 'my': 3, 'brother': 4, 'i': 5, 'go': 6, 'home': 7, 'do': 8, 'you': 9}


2- Sequencing
تبدیل کلمه به اعداد

In [6]:
sequences = tokenizer.texts_to_sequences(sentences)
print(sequences)


[[5, 2, 3, 4], [6, 7], [8, 9, 2, 3, 4]]


In [7]:
new_sentence = ["I like my sister"]
new_sequence = tokenizer.texts_to_sequences(new_sentence)
print(new_sequence)

[[5, 2, 3, 1]]


3- Padding

In [8]:
padded_sequences = pad_sequences(sequences, padding='post', maxlen=10)
print(padded_sequences)
print(type(padded_sequences))


[[5 2 3 4 0 0 0 0 0 0]
 [6 7 0 0 0 0 0 0 0 0]
 [8 9 2 3 4 0 0 0 0 0]]
<class 'numpy.ndarray'>


#Method2
Using TextVectorization Layer

In [9]:
text_vectorization = TextVectorization()
text_vectorization.adapt(sentences)

print(text_vectorization.get_vocabulary())


['', '[UNK]', 'my', 'like', 'brother', 'you', 'i', 'home', 'go', 'do']


In [10]:
encoded_sequences = text_vectorization(sentences)
print(encoded_sequences)
print(type(encoded_sequences))

tf.Tensor(
[[6 3 2 4 0]
 [8 7 0 0 0]
 [9 5 3 2 4]], shape=(3, 5), dtype=int64)
<class 'tensorflow.python.framework.ops.EagerTensor'>
